apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-deployment"
  labels:
    app: "app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "app"
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
        - name: "app"
          image: dazut/asa:latest  # Atualize esta linha com o nome do seu usuário e nome da imagem no Docker Hub
          imagePullPolicy: Always   # Forçar a atualização da imagem sempre que o pod iniciar
          ports:
            - containerPort: 5000
          env:
            - name: PS_DATABASE_URL
              value: mysql://root:password@127.0.0.1:3306/asa
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "app-service"
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: "app"
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: localhost

