# Generated by Django 4.1.5 on 2023-01-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0003_remove_empresa_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("email_verified_at", models.BooleanField(default=False)),
                ("password", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=50)),
                ("rua", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=50)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "cliente",
            },
        ),
    ]
