# Generated by Django 4.1.5 on 2023-01-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("email_verified_at", models.BooleanField(default=False)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "cliente",
                "managed": False,
            },
        ),
    ]
