# Generated by Django 4.1.5 on 2023-01-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={},
        ),
    ]
