# Generated by Django 3.2.16 on 2023-01-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_passwordresets_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokens',
            old_name='user',
            new_name='cliente',
        ),
    ]
