# Generated by Django 3.2.16 on 2023-01-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_user_tokens_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
    ]
