# Generated by Django 4.1.5 on 2023-01-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=48)),
                ("descricao", models.CharField(blank=True, max_length=250, null=True)),
                ("valor", models.FloatField()),
            ],
            options={
                "db_table": "produto",
            },
        ),
    ]
