# Generated by Django 4.1.5 on 2023-01-18 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pedido", "0002_remove_pedido_cliente_endereco_pedido_bairro_and_more"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Itens",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresa.empresa",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pedido.pedido"
                    ),
                ),
            ],
            options={
                "db_table": "itens",
            },
        ),
    ]
