# Generated by Django 3.2.16 on 2023-01-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_itens_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
