# Generated by Django 4.1.5 on 2023-01-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=48)),
                ("cnpj", models.CharField(blank=True, max_length=48, null=True)),
                ("telefone", models.CharField(max_length=48)),
                ("foto", models.CharField(blank=True, max_length=48, null=True)),
                ("cidade", models.CharField(max_length=50)),
                ("rua", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=50)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "empresa",
            },
        ),
    ]
