# Generated by Django 4.1.5 on 2023-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=48)),
                ("cnpj", models.CharField(max_length=48)),
                ("telefone", models.CharField(max_length=48)),
                ("foto", models.CharField(blank=True, max_length=48, null=True)),
                ("produtos", models.ManyToManyField(to="produto.produto")),
            ],
            options={
                "db_table": "empresa",
            },
        ),
    ]
