# Generated by Django 4.1.5 on 2023-01-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=models.CharField(blank=True, default="", max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="complemento",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="foto",
            field=models.CharField(blank=True, default="", max_length=48, null=True),
        ),
    ]
