# Generated by Django 4.1.5 on 2023-01-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_alter_empresa_cnpj_alter_empresa_complemento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="foto",
        ),
    ]
