# Generated by Django 4.1.5 on 2023-01-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("itens", models.CharField(max_length=48)),
                ("fl_super_admin", models.IntegerField()),
                ("fl_alert", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "pedido",
            },
        ),
    ]
