# Generated by Django 4.1.5 on 2023-01-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cliente_nome", models.CharField(max_length=100)),
                ("cliente_endereco", models.CharField(max_length=150)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "pedido",
            },
        ),
    ]
