# Generated by Django 4.1.5 on 2023-01-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="cliente_endereco",
        ),
        migrations.AddField(
            model_name="pedido",
            name="bairro",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="cidade",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="complemento",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="numero",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="rua",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
    ]
